### ISSUE TITLE
Possible to create Mac version?

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/sentencepiece-feedstock#12]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Hi, I was wondering if it might be possible to re-render this package and include a Mac version? I installed it via pip and that worked so I think it should be doable.

If there is interest, I can also try to create the PR but I just wanted to check first.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by BastianZim** [comment]
Just to add, the reason is that I would like to bring https://github.com/conda-forge/python-flair-feedstock to Mac but this seems to be the first step, as https://github.com/conda-forge/bpemb-feedstock seems to also be dependent on this.

**Comment by setu4993** [comment]
Hi @BastianZim, open to receiving PRs on Mac support; that has been a sticking issue for a while now.

The problem occurs because the compilation of the underlying C++ libraries is failing on Mac builds. See https://github.com/conda-forge/sentencepiece-feedstock/pull/5 for my last attempt. I haven't had time since to give it a try.

**Comment by BastianZim** [comment]
Hi @setu4993, thanks for the heads up. I'm going to be on holiday now but I'd try to take a stab at it beginning of January.

**Comment by BastianZim** [comment]
Just to check, should we first create a proper test using the one [provided](https://github.com/google/sentencepiece/tree/master/python/test)? 

That way we can verify any possible underlying mistakes that might not be caught when simply importing the package.

**Comment by setu4993** [comment]
> Just to check, should we first create a proper test using the one [provided](https://github.com/google/sentencepiece/tree/master/python/test)?
> 
> That way we can verify any possible underlying mistakes that might not be caught when simply importing the package.

Would be open to it. I haven't seen that for some of the other packages that I use / maintain, but more tests are better than fewer tests :).

**Comment by BastianZim** [comment]
Ok, will add that to the list. :)

**Comment by h-vetinari** [comment]
> @setu4993: I haven't seen that for some of the other packages that I use / maintain, but more tests are better than fewer tests :).

I think it's good practice to include as much as possible of the upstream test suite also while testing the artefacts being produced by the feedstock. :)

**Comment by BastianZim** [comment]
Quick update from my side:
I've been trying to create a Mac version but wasn't successful yet.

I did try to create the recipe using grayskull which was successful but I cannot install it so I'm now going to create a PR here and then an issue there to see if there is anything they can do.

Besides that, does anyone know what the best practise is regarding test files? Should they be downloaded as well or directly included in the recipe directory?
