### ISSUE TITLE
Changing `CMAKE_INSTALL_LIBDIR` to a relative path

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/sentencepiece-feedstock#47]
According to [the CMake docs]( https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html ), it is recommended that other `CMAKE_INSTALL_*` values are made relative to `CMAKE_INSTALL_PREFIX`

So would recommend changing `CMAKE_INSTALL_LIBDIR` here to be relative (IOW dropping `$PREFIX`)

https://github.com/conda-forge/sentencepiece-feedstock/blob/7bfee3f83b875fbc473bce0badae1e478fc6d09c/recipe/build-lib.sh#L19

**Comment by h-vetinari** [comment]
PRs welcome!

**Comment by h-vetinari** [comment]
This happened as of #48, together with some upstream fixes: https://github.com/google/sentencepiece/commit/1d91514435d3de3c8526d442ec062189415fc832
